### ISSUE TITLE
metatron icon mouseover animation changed?

### ISSUE THREAD

**Issue by exiledsurfer** [interspacechat/interspace.chat#29]
previously, from inactive to mouseover, there was a blend animation from one state to the other. now, on https://deploy-preview-28--noncon-interspace.netlify.com/ the blend animation is from normal state to mouseover state and back to normal state. 

the blend should only happen between two states, ie, on mouseover the blend should stop and show the hover state of the icon

**Comment by geleeroyale** [comment]
Please expand. I can't see a difference in mouseover animation between noncon.interspace.chat and the deploy preview. Or you mean the difference to interspace.chat? It is happening a lot quicker there, because there is no blend (we use no background image on normal state).

The Animation can only start on mouseover, that is the trigger and can't be the finished state - should we make the blend just quicker?

**Comment by exiledsurfer** [comment]
what i mean is that it reverts to the non hover state, when it should stay on the hover state while the mouse is there. in other words i mouse on to the icon, it changes to hover-png then reverts to non-hover.png
